name: Documentation Actions
run-name: Add Preview Link to PR
on:
  pull_request:
    types: [opened]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@v2.4.3
        with:
          message: |
            :wave: Preview link --> https://docs.pieces.app/~${{ github.event.pull_request.number }}