# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Move assigned card
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Project Automation+
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Pieces Support Queue
          column: To triage
          repo-token: ${{ secrets.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 }}
